[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.8"
dependencies = [
    "discord-py>=2.4.0",
    "flask>=3.0.3",
    "requests>=2.32.3",
    "schedule>=1.2.2",
]
